TripKeeper/Models/OperatorEquipment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TripKeeper.Models
{
    public class OperatorEquipment
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public string UserId { get; set; }

        public int RouteNumber { get; set; }
        //EPJ = electric pallet jack
        public int Epj { get; set; }
        public string FluidLeaks { get; set; }
        public string Tires { get; set; }
        public string Forks { get; set; }
        public string HandGuards { get; set; }
        public string SafetyWarnings { get; set; }
        public string OperatorsManual { get; set; }
        public string PowerCord { get; set; }
        public string CapacityPlate { get; set; }
        public string ServiceBreak { get; set; }
        public string SteeringOperation { get; set; }
        public string DrivingControl { get; set; }
        public string HoistControl { get; set; }
        public string Horn { get; set; }
        public string LightsAlarms { get; set; }
        public string HourMeter { get; set; }
        public string BatteryIndicator { get; set; }

        public string ManualForks { get; set; }
        public string Wheels { get; set; }
        public string Maneuverability { get; set; }
        public string Handle { get; set; }
        public string ManualFluidLeaks { get; set; }
        public string ReleaseLever { get; set; }
        public string CracksWear { get; set; }

        public string HandTruckWheels { get; set; }

        public string DockCracks { get; set; }
        public string Bent { get; set; }
        public string MissingHardware { get; set; }
        public string Pins { get; set; }
        public string LiftHandleDamage { get; set; }

        public string Comments { get; set; }

        public string Signature { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime Date { get; set; }
    }
}

TripKeeper/Controllers/OperatorEquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TripKeeper.Data;
using TripKeeper.Models;

namespace TripKeeper.Controllers
{
    public class OperatorEquipmentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public OperatorEquipmentController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: OperatorEquipment
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string userId = _userManager.GetUserId(HttpContext.User);

            var operatorEquipments = await _context.OperatorEquipment.Where(o => o.UserId == userId).ToListAsync();

            return View(operatorEquipments);
            //return View(await _context.OperatorEquipment.ToListAsync());
        }

        // GET: OperatorEquipment/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var operatorEquipment = await _context.OperatorEquipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (operatorEquipment == null)
            {
                return NotFound();
            }

            return View(operatorEquipment);
        }

        // GET: OperatorEquipment/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: OperatorEquipment/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,UserId,RouteNumber,Epj,FluidLeaks,Tires,Forks,HandGuards,SafetyWarnings,OperatorsManual,PowerCord,CapacityPlate,ServiceBreak,SteeringOperation,DrivingControl,HoistControl,Horn,LightsAlarms,HourMeter,BatteryIndicator,ManualForks,Wheels,Maneuverability,Handle,ManualFluidLeaks,ReleaseLever,CracksWear,HandTruckWheels,DockCracks,Bent,MissingHardware,Pins,LiftHandleDamage,Comments,Signature,Date")] OperatorEquipment operatorEquipment)
        {
            if (ModelState.IsValid)
            {

                //Grabbing logged in users id
                string userId = _userManager.GetUserId(HttpContext.User);

                
                ApplicationUser user = _context.Users.Where(a => a.Id == userId).FirstOrDefault();

                //The most recent trip route number
                var mostRecentRouteNumber = _context.Trip.Where(t => t.UserId == userId).OrderByDescending(x => x.StartTime).FirstOrDefault();

                if (mostRecentRouteNumber == null)
                {
                    // user loaded page but doesn't have any trips in their history
                    return View();
                }

                //Assigning the route number here from most recent trip
                operatorEquipment.RouteNumber = mostRecentRouteNumber.RouteNumber;

                //Assigning user ID to the logged in users ID
                operatorEquipment.UserId = user.Id;

                //Assigning the name of the logged in user 
                operatorEquipment.Name = user.FirstName + " " + user.LastName;

                _context.Add(operatorEquipment);
                await _context.SaveChangesAsync();
                return Redirect("~/DotAudit/Create");
            }
            return View(operatorEquipment);
        }

        // GET: OperatorEquipment/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var operatorEquipment = await _context.OperatorEquipment.FindAsync(id);
            if (operatorEquipment == null)
            {
                return NotFound();
            }
            return View(operatorEquipment);
        }

        // POST: OperatorEquipment/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,UserId,RouteNumber,Epj,FluidLeaks,Tires,Forks,HandGuards,SafetyWarnings,OperatorsManual,PowerCord,CapacityPlate,ServiceBreak,SteeringOperation,DrivingControl,HoistControl,Horn,LightsAlarms,HourMeter,BatteryIndicator,ManualForks,Wheels,Maneuverability,Handle,ManualFluidLeaks,ReleaseLever,CracksWear,HandTruckWheels,DockCracks,Bent,MissingHardware,Pins,LiftHandleDamage,Comments,Signature,Date")] OperatorEquipment operatorEquipment)
        {
            if (id != operatorEquipment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(operatorEquipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OperatorEquipmentExists(operatorEquipment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(operatorEquipment);
        }

        // GET: OperatorEquipment/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var operatorEquipment = await _context.OperatorEquipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (operatorEquipment == null)
            {
                return NotFound();
            }

            return View(operatorEquipment);
        }

        // POST: OperatorEquipment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var operatorEquipment = await _context.OperatorEquipment.FindAsync(id);
            _context.OperatorEquipment.Remove(operatorEquipment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OperatorEquipmentExists(int id)
        {
            return _context.OperatorEquipment.Any(e => e.Id == id);
        }
    }
}

TripKeeper/Views/OperatorEquipment/Create.cshtml
@model TripKeeper.Models.OperatorEquipment

@{
    ViewData["Title"] = "Create";
}

<h2 class="text-center">Create New PIT Operator & Equipment Checklist</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="RouteNumber" class="control-label"> </label>
                <input asp-for="RouteNumber" class="form-control" />
                <span asp-validation-for="RouteNumber" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Epj" class="control-label">EPJ</label>
                <input asp-for="Epj" class="form-control" />
                <span asp-validation-for="Epj" class="text-danger"></span>
            </div>
            <h4 class="text-center" style="text-decoration: underline">PIT Inspection</h4>
            <h5>Motor Off Checks</h5>
            <br />
            <div class="form-group">
                <label asp-for="FluidLeaks" class="control-label"></label>
                <input asp-for="FluidLeaks" class="form-control" />
                <span asp-validation-for="FluidLeaks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tires" class="control-label"></label>
                <input asp-for="Tires" class="form-control" />
                <span asp-validation-for="Tires" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Forks" class="control-label"></label>
                <input asp-for="Forks" class="form-control" />
                <span asp-validation-for="Forks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HandGuards" class="control-label"></label>
                <input asp-for="HandGuards" class="form-control" />
                <span asp-validation-for="HandGuards" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafetyWarnings" class="control-label"></label>
                <input asp-for="SafetyWarnings" class="form-control" />
                <span asp-validation-for="SafetyWarnings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OperatorsManual" class="control-label"></label>
                <input asp-for="OperatorsManual" class="form-control" />
                <span asp-validation-for="OperatorsManual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PowerCord" class="control-label"></label>
                <input asp-for="PowerCord" class="form-control" />
                <span asp-validation-for="PowerCord" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacityPlate" class="control-label"></label>
                <input asp-for="CapacityPlate" class="form-control" />
                <span asp-validation-for="CapacityPlate" class="text-danger"></span>
            </div>
            <h5>Motor On Checks</h5>
            <br />
            <div class="form-group">
                <label asp-for="ServiceBreak" class="control-label"></label>
                <input asp-for="ServiceBreak" class="form-control" />
                <span asp-validation-for="ServiceBreak" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SteeringOperation" class="control-label"></label>
                <input asp-for="SteeringOperation" class="form-control" />
                <span asp-validation-for="SteeringOperation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DrivingControl" class="control-label"></label>
                <input asp-for="DrivingControl" class="form-control" />
                <span asp-validation-for="DrivingControl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoistControl" class="control-label"></label>
                <input asp-for="HoistControl" class="form-control" />
                <span asp-validation-for="HoistControl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Horn" class="control-label"></label>
                <input asp-for="Horn" class="form-control" />
                <span asp-validation-for="Horn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LightsAlarms" class="control-label"></label>
                <input asp-for="LightsAlarms" class="form-control" />
                <span asp-validation-for="LightsAlarms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HourMeter" class="control-label"></label>
                <input asp-for="HourMeter" class="form-control" />
                <span asp-validation-for="HourMeter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BatteryIndicator" class="control-label"></label>
                <input asp-for="BatteryIndicator" class="form-control" />
                <span asp-validation-for="BatteryIndicator" class="text-danger"></span>
            </div>
            <h4 class="text-center" style="text-decoration: underline">Manual Pallet Jack Inspection</h4>
            <div class="form-group">
                <label asp-for="ManualForks" class="control-label"></label>
                <input asp-for="ManualForks" class="form-control" />
                <span asp-validation-for="ManualForks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wheels" class="control-label"></label>
                <input asp-for="Wheels" class="form-control" />
                <span asp-validation-for="Wheels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Maneuverability" class="control-label"></label>
                <input asp-for="Maneuverability" class="form-control" />
                <span asp-validation-for="Maneuverability" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Handle" class="control-label"></label>
                <input asp-for="Handle" class="form-control" />
                <span asp-validation-for="Handle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManualFluidLeaks" class="control-label"></label>
                <input asp-for="ManualFluidLeaks" class="form-control" />
                <span asp-validation-for="ManualFluidLeaks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseLever" class="control-label"></label>
                <input asp-for="ReleaseLever" class="form-control" />
                <span asp-validation-for="ReleaseLever" class="text-danger"></span>
            </div>
            <h4 class="text-center" style="text-decoration:underline">Hand Truck/Dolly Inspection</h4>
            <div class="form-group">
                <label asp-for="CracksWear" class="control-label"></label>
                <input asp-for="CracksWear" class="form-control" />
                <span asp-validation-for="CracksWear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HandTruckWheels" class="control-label"></label>
                <input asp-for="HandTruckWheels" class="form-control" />
                <span asp-validation-for="HandTruckWheels" class="text-danger"></span>
            </div>
            <h4 class="text-center" style="text-decoration:underline">Portable Dock Plate Inspection</h4>
            <div class="form-group">
                <label asp-for="DockCracks" class="control-label"></label>
                <input asp-for="DockCracks" class="form-control" />
                <span asp-validation-for="DockCracks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bent" class="control-label"></label>
                <input asp-for="Bent" class="form-control" />
                <span asp-validation-for="Bent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MissingHardware" class="control-label"></label>
                <input asp-for="MissingHardware" class="form-control" />
                <span asp-validation-for="MissingHardware" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pins" class="control-label"></label>
                <input asp-for="Pins" class="form-control" />
                <span asp-validation-for="Pins" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LiftHandleDamage" class="control-label"></label>
                <input asp-for="LiftHandleDamage" class="form-control" />
                <span asp-validation-for="LiftHandleDamage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Signature" class="control-label"></label>
                <input asp-for="Signature" class="form-control" />
                <span asp-validation-for="Signature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TripKeeper/Views/OperatorEquipment/Delete.cshtml
@model TripKeeper.Models.OperatorEquipment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OperatorEquipment</h4>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RouteNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RouteNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Epj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Epj)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FluidLeaks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FluidLeaks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tires)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tires)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Forks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Forks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HandGuards)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HandGuards)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SafetyWarnings)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SafetyWarnings)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OperatorsManual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OperatorsManual)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PowerCord)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PowerCord)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CapacityPlate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacityPlate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceBreak)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceBreak)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SteeringOperation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SteeringOperation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DrivingControl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DrivingControl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoistControl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoistControl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Horn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LightsAlarms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LightsAlarms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HourMeter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HourMeter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BatteryIndicator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BatteryIndicator)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManualForks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManualForks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wheels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wheels)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maneuverability)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maneuverability)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Handle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Handle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManualFluidLeaks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManualFluidLeaks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseLever)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseLever)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CracksWear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CracksWear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HandTruckWheels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HandTruckWheels)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DockCracks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DockCracks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MissingHardware)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MissingHardware)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pins)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pins)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LiftHandleDamage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LiftHandleDamage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Signature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Signature)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TripKeeper/Views/OperatorEquipment/Index.cshtml
@model IEnumerable<TripKeeper.Models.OperatorEquipment>

@{
    ViewData["Title"] = "Index";
}

    <div class="text-center">
        <a class="btn btn-success text-white" asp-controller="OperatorEquipment" asp-action="Create">Create New Entry</a>
    </div>
    <br />
<div class="display">
    <div class="row">
        <div class="table-responsive">
            <table id="table_id" class="display">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Id)</th>
                        <th>@Html.DisplayNameFor(model => model.RouteNumber)</th>
                        <th>@Html.DisplayNameFor(model => model.Epj)</th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RouteNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Epj)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
     </div>
</div>