TripKeeper/Controllers/DotAuditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TripKeeper.Data;
using TripKeeper.Models;

namespace TripKeeper.Controllers
{
    public class DotAuditController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DotAuditController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: DotAudit
        [Authorize]
        public async Task<IActionResult> Index()
        {
            //Grabbing logged in users id
            string userId = _userManager.GetUserId(HttpContext.User);

            var dotAudits = await _context.DotAudit.Where(t => t.UserId == userId).ToListAsync();

            return View(dotAudits);

            //return View(await _context.DotAudit.ToListAsync());
        }

        // GET: DotAudit/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dotAudit = await _context.DotAudit
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dotAudit == null)
            {
                return NotFound();
            }

            return View(dotAudit);
        }

        // GET: DotAudit/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DotAudit/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,UserId,Tractor,Date,DriversLicense,DotCard,ExtraLogBook,PitCard,Tablet,DvirBook,Registration,InsuranceCard,Ifta,LogBook,EldGuide,PermitBook,PostAccidentKit,BlankAccidentReport,OregonFuelPermit,DriverSignature")] DotAudit dotAudit)
        {
            if (ModelState.IsValid)
            {
                //Grabbing logged in users id so when they post the data goes into their account
                string userId = _userManager.GetUserId(HttpContext.User);

                
                ApplicationUser user = _context.Users.Where(a => a.Id == userId).FirstOrDefault();

                // get the user's most recent trip, sorted by the trip start date
                var mostRecentTrip = _context.Trip.Where(t => t.UserId == userId).OrderByDescending(x => x.StartTime).FirstOrDefault();

                if (mostRecentTrip == null)
                {
                    // user loaded page but doesn't have any trips in their history
                    return View();
                }

                // Setting tractor number to the number that was used from that specific trip
                dotAudit.Tractor = mostRecentTrip.Tractor;

                dotAudit.UserId = user.Id;

                //Setting the name of the logged in user into the DotAudit form
                dotAudit.Name = user.FirstName + " " + user.LastName;

                _context.Add(dotAudit);
                await _context.SaveChangesAsync();
                return Redirect("~/EndRouteCheck/Create");
            }
            return View(dotAudit);
        }

        // GET: DotAudit/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dotAudit = await _context.DotAudit.FindAsync(id);
            if (dotAudit == null)
            {
                return NotFound();
            }
            return View(dotAudit);
        }

        // POST: DotAudit/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,UserId,Tractor,Date,DriversLicense,DotCard,ExtraLogBook,PitCard,Tablet,DvirBook,Registration,InsuranceCard,Ifta,LogBook,EldGuide,PermitBook,PostAccidentKit,BlankAccidentReport,OregonFuelPermit,DriverSignature")] DotAudit dotAudit)
        {
            if (id != dotAudit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dotAudit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DotAuditExists(dotAudit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dotAudit);
        }

        // GET: DotAudit/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dotAudit = await _context.DotAudit
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dotAudit == null)
            {
                return NotFound();
            }

            return View(dotAudit);
        }

        // POST: DotAudit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dotAudit = await _context.DotAudit.FindAsync(id);
            _context.DotAudit.Remove(dotAudit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DotAuditExists(int id)
        {
            return _context.DotAudit.Any(e => e.Id == id);
        }
    }
}

TripKeeper/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TripKeeper.Data;
using TripKeeper.Models;

namespace TripKeeper.Controllers
{
    public class TripController : Controller
    {
        private readonly ApplicationDbContext _context;
        //Using the UserManager to accesss logged in users information
        private readonly UserManager<ApplicationUser> _userManager;

        public TripController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Trip
        [Authorize]
        public async Task<IActionResult> Index()
        {
            //Grabbing logged in users ID
            string userId = _userManager.GetUserId(HttpContext.User);

            //Assigning trips to individual user Ids
            var trips = await _context.Trip.Where(t => t.UserId == userId).ToListAsync();



            //Returning a view for the logged in users account
            //Thread.Sleep(3000);
            return View(trips);

            //return View(await _context.Trip.ToListAsync());
        }

        // GET: Trip/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trip
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // GET: Trip/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trip/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IsTeamRoute,Name,UserId,RouteNumber,Tractor,Trailer,StartTime,EndTime,StartMiles,EndingMiles,Inspections,BHPU,XDock,HourlyYard,Chains,Delay,Sleeper,Meals,Pallets,RoadStops,SuperStops,Shuttle,Temp,MiscExpense,Comments,Signature")] Trip trip)
        {
            if (ModelState.IsValid)
            {
                //Grabbing logged in users id
                string userId = _userManager.GetUserId(HttpContext.User);

                //Adding logged in users trip information
                ApplicationUser user = _context.Users.Where(a => a.Id == userId).FirstOrDefault();

                //Assigning trip user ID to the logged in users ID so we can keep track of all trips created
                trip.UserId = user.Id;

                //Assigning the name of the logged in user to the trip full name field 
                trip.Name = user.FirstName + " " + user.LastName;

                _context.Add(trip);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trip);
        }

        // GET: Trip/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trip.FindAsync(id);
            if (trip == null)
            {
                return NotFound();
            }
            return View(trip);
        }

        // POST: Trip/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IsTeamRoute,Name,UserId,RouteNumber,Tractor,Trailer,StartTime,EndTime,StartMiles,EndingMiles,Inspections,BHPU,XDock,HourlyYard,Chains,Delay,Sleeper,Meals,Pallets,RoadStops,SuperStops,Shuttle,Temp,MiscExpense,Comments,Signature")] Trip trip)
        {
            if (id != trip.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Grabbing logged in users id
                    string userId = _userManager.GetUserId(HttpContext.User);

                    //Adding logged in users trip information
                    ApplicationUser user = _context.Users.Where(a => a.Id == userId).FirstOrDefault();

                    //Assigning trip user ID to the logged in users ID so we can keep track of all trips created
                    trip.UserId = user.Id;

                    //Assigning the name of the logged in user to the trip full name field 
                    trip.Name = user.FirstName + " " + user.LastName;

                    _context.Update(trip);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TripExists(trip.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("~/OperatorEquipment/Create");
            }
            return View(trip);
        }

        // GET: Trip/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trip
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // POST: Trip/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trip = await _context.Trip.FindAsync(id);
            _context.Trip.Remove(trip);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TripExists(int id)
        {
            return _context.Trip.Any(e => e.Id == id);
        }
    }
}

TripKeeper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trip Keeper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'" rel="preload">

    @*Datatable CSS*@
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/r-2.2.5/datatables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trip Keeper</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperatorEquipment" asp-action="Index">Operator Equipment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DotAudit" asp-action="Index">DOT Audits</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EndRouteCheck" asp-action="Index">Route Checks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trip" asp-action="Index">Trips</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Trip Keeper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*Datatables CDN*@
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/r-2.2.5/datatables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/r-2.2.5/datatables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table_id').DataTable();
        });

    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>