TripKeeper/Models/EndRouteCheck.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TripKeeper.Models
{
    public class EndRouteCheck
    {
        [Key]
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public int Tractor { get; set; }
        //EPJ = electric pallet jack
        public int Epj { get; set; }
        public DateTime Date { get; set; }
        public string Trailer { get; set; }
        public int RouteNumber { get; set; }

        public string LoadQualitySurvey { get; set; }
        public string TurnInBols { get; set; }
        public string TurnInAllPaperwork { get; set; }
        public string PalletJack { get; set; }
        public string ReturnMisPicks { get; set; }
        public string ClearTrailer { get; set; }
        public string SweepTrailer { get; set; }
        public string ReportTrailer { get; set; }
        public string RetunDvir { get; set; }
        public string ReportEquipmentDamages { get; set; }
        public string StrapsHanding { get; set; }
        public string TrailerShuttle { get; set; }
        public string TrailerLocation { get; set; }

        public string DriverSignature { get; set; }

        //public string OfficeSignature { get; set; }
    }
}

TripKeeper/Controllers/EndRouteCheckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TripKeeper.Data;
using TripKeeper.Models;

namespace TripKeeper.Controllers
{
    public class EndRouteCheckController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public EndRouteCheckController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: EndRouteCheck
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string userId = _userManager.GetUserId(HttpContext.User);

            var endRouteChecks = await _context.EndRouteCheck.Where(a => a.UserId == userId).ToListAsync();

            return View(endRouteChecks);
            //return View(await _context.EndRouteCheck.ToListAsync());
        }

        // GET: EndRouteCheck/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endRouteCheck = await _context.EndRouteCheck
                .FirstOrDefaultAsync(m => m.Id == id);
            if (endRouteCheck == null)
            {
                return NotFound();
            }

            return View(endRouteCheck);
        }

        // GET: EndRouteCheck/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EndRouteCheck/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,Name,Tractor,Epj,Date,Trailer,RouteNumber,LoadQualitySurvey,TurnInBols,TurnInAllPaperwork,PalletJack,ReturnMisPicks,ClearTrailer,SweepTrailer,ReportTrailer,RetunDvir,ReportEquipmentDamages,StrapsHanding,TrailerShuttle,TrailerLocation,DriverSignature")] EndRouteCheck endRouteCheck)
        {
            if (ModelState.IsValid)
            {
                //Grabbing logged in users id
                string userId = _userManager.GetUserId(HttpContext.User);

                //Adding logged in users trip information
                ApplicationUser user = _context.Users.Where(a => a.Id == userId).FirstOrDefault();

                //Assigning trip user ID to the logged in users ID so we can keep track of all trips created
                endRouteCheck.UserId = user.Id;

                //This variable lets us access most recent Trip properties
                var mostRecentTrip = _context.Trip.Where(t => t.UserId == userId).OrderByDescending(x => x.StartTime).FirstOrDefault();

                if (mostRecentTrip == null)
                {
                    return View();
                }

                //This variable lets us access most recent OperatorEquipment properties
                var mostRecentEpj = _context.OperatorEquipment.Where(e => e.UserId == userId).OrderByDescending(z => z.Date).FirstOrDefault();

                if (mostRecentEpj == null)
                {
                    return View();
                }

                //Assigning tractor number that was used on the most recent trip
                endRouteCheck.Tractor = mostRecentTrip.Tractor;

                //Assigning trailer number that was used on most recent trip
                endRouteCheck.Trailer = mostRecentTrip.Trailer;

                //Assigning routenumber that was used on the most recent trip
                endRouteCheck.RouteNumber = mostRecentTrip.RouteNumber;

                //Assigning Electric Pallet Jack(EPJ) number 
                endRouteCheck.Epj = mostRecentEpj.Epj;
                

                //Assigning the name of the logged in user to the trip full name field 
                endRouteCheck.Name = user.FirstName + " " + user.LastName;

                _context.Add(endRouteCheck);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(endRouteCheck);
        }

        // GET: EndRouteCheck/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endRouteCheck = await _context.EndRouteCheck.FindAsync(id);
            if (endRouteCheck == null)
            {
                return NotFound();
            }
            return View(endRouteCheck);
        }

        // POST: EndRouteCheck/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,Name,Tractor,Epj,Date,Trailer,RouteNumber,LoadQualitySurvey,TurnInBols,TurnInAllPaperwork,PalletJack,ReturnMisPicks,ClearTrailer,SweepTrailer,ReportTrailer,RetunDvir,ReportEquipmentDamages,StrapsHanding,TrailerShuttle,TrailerLocation,DriverSignature")] EndRouteCheck endRouteCheck)
        {
            if (id != endRouteCheck.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(endRouteCheck);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EndRouteCheckExists(endRouteCheck.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(endRouteCheck);
        }

        // GET: EndRouteCheck/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endRouteCheck = await _context.EndRouteCheck
                .FirstOrDefaultAsync(m => m.Id == id);
            if (endRouteCheck == null)
            {
                return NotFound();
            }

            return View(endRouteCheck);
        }

        // POST: EndRouteCheck/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var endRouteCheck = await _context.EndRouteCheck.FindAsync(id);
            _context.EndRouteCheck.Remove(endRouteCheck);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EndRouteCheckExists(int id)
        {
            return _context.EndRouteCheck.Any(e => e.Id == id);
        }
    }
}

TripKeeper/Views/EndRouteCheck/Create.cshtml
@model TripKeeper.Models.EndRouteCheck

@{
    ViewData["Title"] = "Create";
}

<h2 class="text-center">Create New End Route Check</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="Tractor" class="control-label"></label>
                <input asp-for="Tractor" class="form-control" />
                <span asp-validation-for="Tractor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Epj" class="control-label"></label>
                <input asp-for="Epj" class="form-control" />
                <span asp-validation-for="Epj" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Trailer" class="control-label"></label>
                <input asp-for="Trailer" class="form-control" />
                <span asp-validation-for="Trailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RouteNumber" class="control-label"></label>
                <input asp-for="RouteNumber" class="form-control" />
                <span asp-validation-for="RouteNumber" class="text-danger"></span>
            </div>*@
            <h4>Action Required: Enter initials</h4>
            <div class="form-group">
                <label asp-for="LoadQualitySurvey" class="control-label"></label>
                <input asp-for="LoadQualitySurvey" class="form-control" />
                <span asp-validation-for="LoadQualitySurvey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TurnInBols" class="control-label"></label>
                <input asp-for="TurnInBols" class="form-control" />
                <span asp-validation-for="TurnInBols" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TurnInAllPaperwork" class="control-label"></label>
                <input asp-for="TurnInAllPaperwork" class="form-control" />
                <span asp-validation-for="TurnInAllPaperwork" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PalletJack" class="control-label"></label>
                <input asp-for="PalletJack" class="form-control" />
                <span asp-validation-for="PalletJack" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReturnMisPicks" class="control-label"></label>
                <input asp-for="ReturnMisPicks" class="form-control" />
                <span asp-validation-for="ReturnMisPicks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClearTrailer" class="control-label"></label>
                <input asp-for="ClearTrailer" class="form-control" />
                <span asp-validation-for="ClearTrailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SweepTrailer" class="control-label"></label>
                <input asp-for="SweepTrailer" class="form-control" />
                <span asp-validation-for="SweepTrailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReportTrailer" class="control-label"></label>
                <input asp-for="ReportTrailer" class="form-control" />
                <span asp-validation-for="ReportTrailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RetunDvir" class="control-label"></label>
                <input asp-for="RetunDvir" class="form-control" />
                <span asp-validation-for="RetunDvir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReportEquipmentDamages" class="control-label"></label>
                <input asp-for="ReportEquipmentDamages" class="form-control" />
                <span asp-validation-for="ReportEquipmentDamages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StrapsHanding" class="control-label"></label>
                <input asp-for="StrapsHanding" class="form-control" />
                <span asp-validation-for="StrapsHanding" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrailerShuttle" class="control-label"></label>
                <input asp-for="TrailerShuttle" class="form-control" />
                <span asp-validation-for="TrailerShuttle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrailerLocation" class="control-label"></label>
                <input asp-for="TrailerLocation" class="form-control" />
                <span asp-validation-for="TrailerLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriverSignature" class="control-label"></label>
                <input asp-for="DriverSignature" class="form-control" />
                <span asp-validation-for="DriverSignature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TripKeeper/Views/EndRouteCheck/Delete.cshtml
@model TripKeeper.Models.EndRouteCheck

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EndRouteCheck</h4>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tractor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tractor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Epj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Epj)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RouteNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RouteNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoadQualitySurvey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoadQualitySurvey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TurnInBols)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TurnInBols)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TurnInAllPaperwork)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TurnInAllPaperwork)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PalletJack)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PalletJack)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnMisPicks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnMisPicks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClearTrailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClearTrailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SweepTrailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SweepTrailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportTrailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportTrailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RetunDvir)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RetunDvir)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportEquipmentDamages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportEquipmentDamages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StrapsHanding)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StrapsHanding)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrailerShuttle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrailerShuttle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrailerLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrailerLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DriverSignature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DriverSignature)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TripKeeper/Views/EndRouteCheck/Details.cshtml
@model TripKeeper.Models.EndRouteCheck

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>EndRouteCheck</h4>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tractor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tractor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Epj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Epj)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RouteNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RouteNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoadQualitySurvey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoadQualitySurvey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TurnInBols)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TurnInBols)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TurnInAllPaperwork)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TurnInAllPaperwork)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PalletJack)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PalletJack)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnMisPicks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnMisPicks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClearTrailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClearTrailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SweepTrailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SweepTrailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportTrailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportTrailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RetunDvir)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RetunDvir)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportEquipmentDamages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportEquipmentDamages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StrapsHanding)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StrapsHanding)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrailerShuttle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrailerShuttle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrailerLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrailerLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DriverSignature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DriverSignature)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TripKeeper/Views/EndRouteCheck/Index.cshtml
@model IEnumerable<TripKeeper.Models.EndRouteCheck>

@{
    ViewData["Title"] = "Index";
}

    <div class="text-center">
        <a class="btn btn-success text-white" asp-controller="EndRouteCheck" asp-action="Create">Create New Entry</a>
    </div>
    <br />
<div class="display">
    <div class="row">
        <div class="table-responsive">
            <table id="table_id" class="display responsive nowrap" width="100%">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Id)</th>
                        <th>@Html.DisplayNameFor(model => model.Tractor)</th>
                        <th>@Html.DisplayNameFor(model => model.Date)</th>
                        <th>@Html.DisplayNameFor(model => model.RouteNumber)</th>
                        <th>@Html.DisplayNameFor(model => model.DriverSignature)</th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tractor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RouteNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DriverSignature)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
     </div>
</div>